name: Code Quality

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:    
      - '*'

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Lint
        run: |
          echo "Run Linter"
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Unit Test
        run: echo "Unit Test"
  run-integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Integration Test
        run: echo "Integration Test"
  run-code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Code Coverage
        run: echo "Code Coverage"